### ISSUE TITLE
move location of ~/zwm.log to ~/.local/share/xorg/zwm.log

### ISSUE THREAD

**Issue by ranjandatta** [Yazeed1s/zwm#2]
To keep in line with [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

**Comment by Yazeed1s** [comment]
@ranjandatta Thanks for this. It make sense to move it to that location, I'll do that

**Comment by Yazeed1s** [comment]
Done in #4
