### ISSUE TITLE
Hot reload without exec sentences reload (like i3 exec)

### ISSUE THREAD

**Issue by Lang-Lovdog** [Yazeed1s/zwm#23]
## Issue Type
- [ ] Bug Report
- [ x] Feature Request
- [ ] Enhancement

## Description
I would like to reload my zwm without reloading the whole exec sentences.

I'll treat it more like a feature request rather than a Bug (because the way zwm actually is)

Currently I have an automatic terminal open when starting zwm session;
I'll give the command used at start:
´exec = ["alacritty", "--command", "/bin/clifm","~"]´

For more info:
Void Linux x64
DELL Inspiron 5567
Core i7 7thGen  | 4 Cores

**Comment by Yazeed1s** [comment]
@Lang-Lovdog Oh I see why that needs to be changed. I am already working on a PR that fixes another bug, I'll add the fix for issue to it and get it merged soon.

**Comment by Lang-Lovdog** [comment]
> @Lang-Lovdog Oh I see why that needs to be changed. I am already working on a PR that fixes another bug, I'll add the fix for this issue to it and get it merged soon.

Thanks!, I really like this project. I migrated from i3; I can say zwm fits me better.

**Comment by Yazeed1s** [comment]
@Lang-Lovdog glad you found it that way!
