### ISSUE TITLE
exec command runs twice

### ISSUE THREAD

**Issue by Lang-Lovdog** [Yazeed1s/zwm#24]
## Issue Type
- [ x] Bug Report
- [ ] Feature Request
- [ ] Enhancement

## Description
When opening zwm, it runs twice the command.
Took a look at the code... suspecting about fork() function.
But currently can't tell.

## Steps to Reproduce (for Bug Reports)
1.  Set any command which can have more than one instance running (like `exec = "alacritty"`)
2. Run zwm instance

## Expected Behavior
Run command

## Actual Behavior
Command running twice

## Checklist
- [x ] I have searched for duplicate issues to ensure this is not a duplicate.
---

**Comment by Yazeed1s** [comment]
@Lang-Lovdog I am not able to reproduce this bug, i added exec = "alacritty" and the window maps only once, also btop shows no duplicate instances of it. Can you share the first lines of your config? Also are you running the latest version?

**Comment by Yazeed1s** [comment]
Okay, i'll see if i can reproduce it with your config

**Comment by Yazeed1s** [comment]
With `exec = ["alacritty", "--command", "clifm"]`, which process was ran twice on your end? I tried the same `exec` command and btop shows a single `alacritty` instance and a single `clifm` instance, which is expected.

**Comment by Lang-Lovdog** [comment]
In my computer when starting zwm it runs two different alacritty instances with clifm opened each.

**Comment by Yazeed1s** [comment]
I understand the issue, but I can't reproduce it on my end. I added a bunch of programs to the config file, and none of them executed twice. Perhaps you have the same programs listed in your `.xinit` file?. My guess is that these processes are set to start automatically when the X window manager launches elsewhere in your system.

**Comment by Lang-Lovdog** [comment]
Actually, it doesn't, because I didn't use alacritty before zwm. xfce4-terminal glitches a lot with tiling wms but was the one I used.

At this point I'll check profile and other stuff for any duplicated processes. I'll tell if anything.

**Comment by Yazeed1s** [comment]
To decide if zwm is actually causing the issue, i would suggest you comment out all the `exec` statements and then start zwm and see if the processes launch on start. If they launch then indeed some other script in your system is causing the issue, if not I will dig deeper into the problem later this week

**Comment by Yazeed1s** [comment]
@Lang-Lovdog,
You’re right! I was able to reproduce the issue. It’s related to `fork`. if a child process fails (with execvp), it doesn't exit properly and causes the parent to re-run some commands, which is why they execute twice. I’ll fix it so failed processes exit cleanly without triggering retries.

**Comment by Yazeed1s** [comment]
The fix is now pushed to main branch. See if the issue still persists

**Comment by Lang-Lovdog** [comment]
Yeah, it's fixed now.

So, the reason for the rerun was an error in some exec?

Then I need to check out the zwm log.

Sorry for not answering before, I got busy.

**Comment by Yazeed1s** [comment]
Yeah it was an error in the exec statements, it could be that one of the commands isn't wrapped in quotation marks or the executable is misused or does not exist in the system at all.
