### ISSUE TITLE
sudo make install cannot install due to what seems to be a missing directory

### ISSUE THREAD

**Issue by lDEVinux** [Yazeed1s/zwm#3]
When installing, it gives me an error saying `xcb/xcb_ewmh.h: No such file or directory`
It seems to be completely missing so maybe I am missing something? I have tried redoing it but I cannot find anything.

**Comment by Yazeed1s** [comment]
Yes that's a dependency issue. I will update the readme file tonight and specify all the dependencies. In the meantime, you can install libxcb to resolve this.

**Comment by Yazeed1s** [comment]
From the make file, those are the dependencies '-lxcb -lxcb-util -lxcb-keysyms -lxcb-ewmh -lxcb-icccm' needed to build zwm

**Comment by Yazeed1s** [comment]
@lDEVinux The readme file now includes the dependencies!

**Comment by lDEVinux** [comment]
I've installed all the dependencies yet it gives me the error: 
`In file included from src/zwm.c:32:
src/zwm.h:33:10: fatal error: xcb/xcb_icccm.h: No such file or directory
   33 | #include <xcb/xcb_icccm.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:19: src/zwm.o] Error 1
`
I'm on an Ubuntu-based distro. It seems the packages you provided are in the Arch repos. I've installed all the packages, including libxcb-icccm4. Any ideas?

**Comment by Yazeed1s** [comment]
Yeah it's clearly not recognizing xcb-icccm in your machine. Maybe libxcb-icccm4-dev is required too? Try installing this package and see if it resolves your issue. https://packages.ubuntu.com/search?searchon=sourcenames&keywords=xcb-util-wm. If not, make sure those packages reside in accessible directory.

**Comment by ClassickTech** [comment]
I am getting the same error on NixOS:
In file included from src/zwm.h:32,
                 from src/zwm.c:32:
src/type.h:35:10: fatal error: xcb/xcb.h: No such file or directory
   35 | #include <xcb/xcb.h>

**Comment by lDEVinux** [comment]
> Yeah it's clearly not recognizing xcb-icccm in your machine. Maybe libxcb-icccm4-dev is required too? Try installing this package and see if it resolves your issue. https://packages.ubuntu.com/search?searchon=sourcenames&keywords=xcb-util-wm. If not, make sure those packages reside in accessible directory.

Yeah I've installed libxcb-icccm4-dev but now it seems it can't find:
`src/zwm.c:47:10: fatal error: xcb/xcb_keysyms.h: No such file or directory
   47 | #include <xcb/xcb_keysyms.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:19: src/zwm.o] Error 1
`
Any ideas? I do have all the packages there installed.
